// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (BkUser, error)
	Createaddress(ctx context.Context, arg CreateaddressParams) (BkAddress, error)
}

var _ Querier = (*Queries)(nil)
